# lightning==2.3.0.dev0
seed_everything: 1
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 50
  use_distributed_sampler: false
  limit_train_batches: 800
  log_every_n_steps: 2
  default_root_dir: ./results
  accumulate_grad_batches: 8
model:
  forecaster:
    class_path: probts.model.forecaster.prob_forecaster.GRU_NVP
    init_args:
      enc_hidden_size: 40
      enc_num_layers: 2
      enc_dropout: 0.1
      n_blocks: 2
      hidden_size: 100
      n_hidden: 2
      batch_norm: true
      conditional_length: 100
      dequantize: false
      use_lags: false
      use_feat_idx_emb: false
      use_time_feat: false
      feat_idx_emb_dim: 1
      use_scaling: true
  num_samples: 100
  learning_rate: 0.001
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: tourism_monthly
      context_length_factor: 3
      split_val: true
      scaler: identity # identity, standard, temporal
  batch_size: 1
  test_batch_size: 1
  num_workers: 8
