# lightning==2.3.0.dev0
seed_everything: 0
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 40
  use_distributed_sampler: false
  limit_train_batches: 10
  log_every_n_steps: 1
  default_root_dir: ./exps
  num_sanity_val_steps: 0
model:
  forecaster:
    class_path: probts.model.forecaster.pretrain.Moirai
    init_args:
      variate_mode: S
      patch_size: auto
      model_size: base
      scaling: true
  num_samples: 100
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: [etth1, etth2]
      path: ./datasets
      split_val: true
      scaler: standard # identity, standard
      context_length: 96
      history_length: 96 # needed for different freq dataset
      prediction_length: [[48, 96], [48, 96]]
      is_pretrain: true
      var_specific_norm: False
  batch_size: 64
  test_batch_size: 64
  num_workers: 0