# lightning==2.3.0.dev0
seed_everything: 1
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 50
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  default_root_dir: ./exps
  accumulate_grad_batches: 4
model:
  forecaster:
    class_path: probts.model.forecaster.point_forecaster.PatchTST
    init_args:
      stride: 8
      patch_len: 16
      dropout: 0.3
      f_hidden_size: 16
      n_layers: 3
      n_heads: 4
      fc_dropout: 0.2
      head_dropout: 0
      individual: true
  learning_rate: 0.0001
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: [etth1, etth2]
      path: ./datasets
      split_val: true
      scaler: identity # identity, standard, temporal
      context_length: 96
      prediction_length: 96
      is_pretrain: true
  batch_size: 32
  test_batch_size: 32
  num_workers: 8