# lightning==2.3.0.dev0
seed_everything: 1
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 50
  use_distributed_sampler: false
  limit_train_batches: 200
  log_every_n_steps: 1
  accumulate_grad_batches: 2
  default_root_dir: ./results
model:
  forecaster:
    class_path: probts.model.forecaster.point_forecaster.DLinearEncoder
    init_args:
      individual: true
      kernel_size: 25
      use_lags: false
      use_feat_idx_emb: false
      use_time_feat: false
  learning_rate: 0.001
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: electricity_ltsf
      split_val: true
      scaler: standard # identity, standard, temporal
      context_length: 96
      prediction_length: 96
  batch_size: 16
  test_batch_size: 16
  num_workers: 8
