# lightning==2.3.0.dev0
seed_everything: 1
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 50
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  default_root_dir: ./results
  accumulate_grad_batches: 4
model:
  forecaster:
    class_path: probts.model.forecaster.prob_forecaster.TimeGrad
    init_args:
      loss_type: l2
      diff_steps: 100
      beta_end: 0.1
      beta_schedule: linear
      conditional_length: 200
      enc_hidden_size: 64
      enc_num_layers: 2
      enc_dropout: 0.1
      use_lags: true
      use_feat_idx_emb: true
      use_time_feat: true
      feat_idx_emb_dim: 1
      use_scaling: true
  num_samples: 100
  learning_rate: 0.001
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: illness_ltsf
      split_val: true
      scaler: identity # identity, standard, temporal
      context_length: 36
      prediction_length: 36
  batch_size: 16
  test_batch_size: 16
  num_workers: 8
