# lightning==2.3.0.dev0
seed_everything: 1
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 50
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  default_root_dir: ./results
model:
  forecaster:
    class_path: probts.model.forecaster.prob_forecaster.GRU_MAF
    init_args:
      enc_num_layers: 2
      enc_hidden_size: 40
      enc_dropout: 0.1
      n_blocks: 3
      hidden_size: 100
      n_hidden: 2
      batch_norm: true
      conditional_length: 200
      dequantize: true
      use_lags: true
      use_feat_idx_emb: true
      use_time_feat: true
      feat_idx_emb_dim: 1
      use_scaling: true
  num_samples: 100
  learning_rate: 0.001
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: wiki2000_nips
      split_val: true
      scaler: identity # identity, standard, temporal
  batch_size: 64
  test_batch_size: 64
  num_workers: 8
