from .mean import MeanForecaster
from .linear import LinearForecaster
from .patchtst import PatchTST
from .transformer import TransformerForecaster
from .gru import GRUForecaster
from .dlinear import DLinear
from .nlinear import NLinear
from .nhits import NHiTS
from .timesnet import TimesNet
from .itransformer import iTransformer
from .autoformer import Autoformer