# lightning==2.3.0.dev0
seed_everything: 0
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 1
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  default_root_dir: ./results
model:
  forecaster:
    class_path: probts.model.forecaster.prob_forecaster.Moirai
    init_args:
      variate_mode: M
      patch_size: auto
      model_size: base
      scaling: true
  num_samples: 100
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: weather_ltsf
      split_val: true
      scaler: standard # identity, standard, temporal
      var_specific_norm: true
      context_length: 96
  batch_size: 64
  test_batch_size: 64
  num_workers: 8